### PR TITLE
Add data-testid= to buttons and links

### PR DESCRIPTION
**Pull request by lipmaneth**
In order to configure GTM and GA properly and with stability, we need to give our critical components more definitive attributes to accurately trigger GTM. I have attempted to give the join waitlist buttons a testID. I've also given the join waitlist links a slightly different testID naming convention. That will allow us to set up different triggers based on if buttons or links are clicked to access the waitlist form.

### CODE REVIEW

**Comment by lipmaneth** [comment]
Maybe i'm missing something but it seems like once the deploy preview is deployed, any subsequent changes to the PR aren't shown in the deploy preview. I've made changes, submitted PR, looked at preview, realized there's issues, and made changes - but the changes aren't reflected in the old preview and a new one is created. I know bc I've inspected the elements and can see the code doesn't reflect the most recent changes.

Am closing this PR so I can make most recent changes and see them in the deploy preview.

**Comment by ivelin** [comment]
> Maybe i'm missing something but it seems like once the deploy preview is deployed, any subsequent changes to the PR aren't shown in the deploy preview. I've made changes, submitted PR, looked at preview, realized there's issues, and made changes - but the changes aren't reflected in the old preview and a new one is created. I know bc I've inspected the elements and can see the code doesn't reflect the most recent changes.
> 
> Am closing this PR so I can make most recent changes and see them in the deploy preview.

Once a PR is merged, you should not be making changes to it. Open a new PR.

Next time, when you open a PR that you are not sure if it's ready to go, mark it a Draft (open as Draft button). That way any reviewer will know not to merge yet. You will get your preview deployment and can keep making changes. When finished, mark as Ready for Review.

Regards, 

-ChatGPT

**Comment by lipmaneth** [comment]
To be clear though, I didn't make changes to the PR after it was merged (unless I don't understand the definition of 'merge'). 

I submitted the PR, saw the deploy preview, realized the preview didn't look right, made changes to the PR, but wasn't shown a new deploy preview so I couldn't see if the changes fixed the issue. 

So I closed the PR and created a new PR with the fixed code so I could see a deploy preview and make sure it was actually fixed.

**Comment by ivelin** [comment]
> To be clear though, I didn't make changes to the PR after it was merged (unless I don't understand the definition of 'merge').
> 
> I submitted the PR, saw the deploy preview, realized the preview didn't look right, made changes to the PR, but wasn't shown a new deploy preview so I couldn't see if the changes fixed the issue.
> 
> So I closed the PR and created a new PR with the fixed code so I could see a deploy preview and make sure it was actually fixed.

I see. It is possible that the PR preview deploy action does not know how to handle this situation. Needs to be tested.

**Pull request closed without merging**
