### PR TITLE
Updating the site nav

### PR DESCRIPTION
**Pull request by lipmaneth**
Online Browser Testing to link to guardianui.com, AI Test automation to link to guardianui.com/ai, and Docs to link to https://guardianui.gitbook.io/beta-documentation/

I will also update for the AI LP.

### CODE REVIEW

**Review by ivelin — CHANGES_REQUESTED** [review]
See failing checks. Let's fix and add more tests to prevent running into more underwater rocks.

**Comment by lipmaneth** [comment]
@ivelin looks like this the test that keeps failing? The most recent commmits include the correct data testid so not sure why it would still be failing. https://github.com/GuardianUI/landing-page/blob/main/tests/home-page-refexp.spec.ts

**Comment by ivelin** [comment]
> @ivelin looks like this the test that keeps failing? The most recent commmits include the correct data testid so not sure why it would still be failing. https://github.com/GuardianUI/landing-page/blob/main/tests/home-page-refexp.spec.ts

Right. That's because the tests are running against the live website not the current code view in the PR. I'm working on fixing that.

Is this PR ready for merge otherwise?

**Comment by lipmaneth** [comment]
> > @ivelin looks like this the test that keeps failing? The most recent commmits include the correct data testid so not sure why it would still be failing. https://github.com/GuardianUI/landing-page/blob/main/tests/home-page-refexp.spec.ts
> 
> Right. That's because the tests are running against the live website not the current code view in the PR. I'm working on fixing that.
> 
> Is this PR ready for merge otherwise?

Got it. Yes only thing confusing is why this nav structure isn't showing in the deploy preview on the gui.com/AI page. The code is there. https://github.com/GuardianUI/landing-page/blob/lipmaneth-patch-1/ai.html

**Comment by lipmaneth** [comment]
@ivelin is this ready to merge ya think?

**Comment by ivelin** [comment]
> @ivelin is this ready to merge ya think?

It looks fine to me, but I am not sure what nav structure you are expecting to show that is not.

**Comment by lipmaneth** [comment]
> > @ivelin is this ready to merge ya think?
> 
> It looks fine to me, but I am not sure what nav structure you are expecting to show that is not.

It's fine. Matt just showed me I was looking in the wrong spot.

**Pull request merged**
