### PR TITLE
Delete preview.yml

### PR DESCRIPTION
**Pull request by lipmaneth**
We don't need this anymore since we now have Netlify.

### CODE REVIEW

**Comment by ivelin** [comment]
Great. It was leaving too much trash behind. You will need to tinker with the github pages settings to move the domain over to netlify.

**Comment by lipmaneth** [comment]
I was reading about that. What's the benefit of moving the domain over to netlify?

**Comment by ivelin** [comment]
Good question. No big benefit for our current setup. 

As the site becomes more complex , Netlify's benefits become more interesting. Caching, SEO, telemetry, A/B, forms, serverless functions, etc.
https://docs.netlify.com/site-deploys/split-testing/

**Comment by lipmaneth** [comment]
Oh that's cool. I'll add it to my list but sounds like it doesn't need to be a top priority atm.

**Pull request merged**
